# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-29 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DbController', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiariestable',
            name='email',
            field=models.EmailField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
