# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-29 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DbController', '0002_beneficiariestable_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationstable',
            name='expiry',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
